main:
  project_name: dynamic risk assessment
  experiment_name: development
  steps: all
  mlflow_logging: True

ingestion:
  ingestion_path     : "practicedata"
  ingestion_filename : ['*']
  ingested_data_path : "ingesteddata" 
  output_path        : "ingesteddata" 
  output_filename    : "finaldata.csv"
  ingested_files_log : "ingestedfiles.txt"
  ingested_filename  : "finaldata.csv"
  # numeric_columns    :  ["lastmonth_activity", "lastyear_activity", "number_of_employees"] 

training:
  output_model_path  : "practicemodels" 

scoring:
  test_data_path: "testdata"
  report_folder: "report"
  prediction_output: "predictions.csv"
  score_filename: "latestscore.txt"
  # parent_folder: "../../"

prod_deployment:
  prod_deployment_path: "production_deployment" 
  output_model_name: "trainedmodel.pkl"

diagnostics:
  data_folder         : "practicedata"
  data_files          : ["*"]
  report_folder       : "report"
  prediction_output   : "predictions_diag.csv"
  score_filename      : "latestscore_diag.txt"
  temp_folder         : "temp"
  timing_filename     : "timings_diag.csv"

num_features:
- lastmonth_activity
- lastyear_activity
- number_of_employees
- exited

reporting:
  test_data_path : "testdata"

logistic_regression_params:
- C : 1.0
  class_weight : None 
  dual : False
  fit_intercept : True
  intercept_scaling : 1 
  l1_ratio : None
  max_iter : 100
  n_jobs : None
  penalty : 'l2'
  random_state : 0 
  solver : 'liblinear' 
  tol : 0.0001
  verbose : 0
  warm_start : False

